### PR TITLE
Lookup donation address

### PR DESCRIPTION
**Pull request by dkackman**
https://github.com/Datalayer-Storage/Distributed-Internet-Gateway/issues/29

### CODE REVIEW

**Comment by MichaelTaylor3D** [comment]
@dkackman this is does the donation address but actually i was thinking the donation address should be hardcoded to a xch split for the contributers. 

The tipping address is the thing we want to resolve dynamically

**Comment by dkackman** [comment]
> @dkackman this is does the donation address but actually i was thinking the donation address should be hardcoded to a xch split for the contributers.

How would that work? address of a shared wallet?

> 
> The tipping address is the thing we want to resolve dynamically

`xch_address` is the "tipping address"?

**Comment by MichaelTaylor3D** [comment]
we can just go to xch split and generate a split address for each other.

the nodes actual address would be the tipping address.

**Comment by dkackman** [comment]
changes made. please re-review

**Review by MichaelTaylor3D — APPROVED** [review]

**Pull request merged**
